# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import talentshow.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', localflavor.us.models.PhoneNumberField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(max_length=500)),
                ('props_info', models.CharField(blank=True, max_length=500, null=True)),
                ('time_registered', models.DateTimeField(auto_now_add=True)),
                ('reminder_email', models.BooleanField(default=True)),
                ('reminder_text', models.BooleanField(default=False)),
                ('secret', models.CharField(default=talentshow.models._generate_secret, max_length=40, unique=True)),
                ('sent_reminder_email', models.BooleanField(default=False)),
                ('sent_reminder_text', models.BooleanField(default=False)),
                ('sent_slot_reminder_email', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AuditionSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AuditionSignUpReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditionSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('auditioner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talentshow.Auditioner')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentshow.AuditionSession')),
            ],
        ),
    ]
